version: '3'

services:
  utility:
    image: buzzingpixel/utility:1.1.0
    container_name: utility-corbomite-flash-data
    environment:
      HOSTNAME: utility-corbomite-flash-data
    volumes:
      - .:/app
      - db-volume:/db-volume
    command: bash -c "chmod +x /scripts/devUtilityScript.sh && /scripts/devUtilityScript.sh"
  web:
    image: buzzingpixel/nginx:1.0.2
    container_name: nginx-corbomite-flash-data
    environment:
      HOSTNAME: nginx-corbomite-flash-data
    ports:
      - "16159:80"
    volumes:
      - .:/app:delegated
      - ./serverConfig/nginx/site.test.conf:/etc/nginx/conf.d/site.conf:delegated
  php:
    image: buzzingpixel/php7.2:1.0.6
    container_name: php-corbomite-flash-data
    environment:
      HOSTNAME: php-corbomite-flash-data
      COMPOSER_HOME: /composer-home-volume
    volumes:
      - .:/app:delegated
      - ./serverConfig/php/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini:delegated
      - ./serverConfig/php/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini:delegated
      - composer-home-volume:/composer-home-volume:delegated
  db:
    image: buzzingpixel/mariadb:2.0.1
    container_name: db-corbomite-flash-data
    restart: always
    environment:
      HOSTNAME: db-corbomite-flash-data
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: site
      MYSQL_DATABASE: site
      MYSQL_PASSWORD: secret
    user: "1000:50"
    volumes:
      - .:/app:delegated
      - db-volume:/var/lib/mysql
    ports:
      - "37388:3306"

volumes:
  composer-home-volume:
  db-volume:
